package cgss_collect;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author YAMATO
 */
public class CGSS_Collect_GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    //CGSS_Collect CAPI;
    private static final int singleStaminaPlay = 19;
    private static final int doubleStaminaPlay = 38;
    private static final int singleStaminaCollect = 53;
    private static final int doubleStaminaCollect = 106;
    public CGSS_Collect_GUI() {
        initComponents();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PLvSpinner = new javax.swing.JSpinner();
        PLvLabel = new javax.swing.JLabel();
        EventHrLabel = new javax.swing.JLabel();
        EventHrSpinner = new javax.swing.JSpinner();
        StarLabel = new javax.swing.JLabel();
        StarSpinner = new javax.swing.JSpinner();
        AutoRecStamLabel = new javax.swing.JLabel();
        AutoRecStamTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Stam19Label = new javax.swing.JLabel();
        Stam19TextField = new javax.swing.JTextField();
        Stam38Label = new javax.swing.JLabel();
        Stam38TextField = new javax.swing.JTextField();
        CollectedLabel = new javax.swing.JLabel();
        CollectedTextField = new javax.swing.JTextField();
        CollectedPTLabel = new javax.swing.JLabel();
        CollectedPTTextField = new javax.swing.JTextField();
        CollectedToPTLabel = new javax.swing.JLabel();
        CollectedToPTTextField = new javax.swing.JTextField();
        TotalPTLabel = new javax.swing.JLabel();
        TotalPTTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CGSS 集物PT計算");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(370, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 410));

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CGSS 集物PT計算");

        PLvSpinner.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        PLvSpinner.setModel(new javax.swing.SpinnerNumberModel(200, 1, 500, 1));
        PLvSpinner.setToolTipText("max: 500");
        PLvSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PLvSpinnerStateChanged(evt);
            }
        });

        PLvLabel.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        PLvLabel.setText("PLv:");

        EventHrLabel.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        EventHrLabel.setText("活動時數:");

        EventHrSpinner.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        EventHrSpinner.setModel(new javax.swing.SpinnerNumberModel(174, 174, 222, 1));
        EventHrSpinner.setToolTipText("max: 222");
        EventHrSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EventHrSpinnerStateChanged(evt);
            }
        });

        StarLabel.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        StarLabel.setText("石頭量:");

        StarSpinner.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        StarSpinner.setModel(new javax.swing.SpinnerNumberModel(1000, 3, 75000, 1));
        StarSpinner.setToolTipText("max: 75,000");
        StarSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                StarSpinnerStateChanged(evt);
            }
        });

        AutoRecStamLabel.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        AutoRecStamLabel.setText("自然回體:");

        AutoRecStamTextField.setEditable(false);
        AutoRecStamTextField.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        AutoRecStamTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        AutoRecStamTextField.setText(""+((Integer)EventHrSpinner.getValue() * 12));
        AutoRecStamTextField.setToolTipText("自然回體量");

        Stam19Label.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        Stam19Label.setText("1倍消體場次(19體):");

        Stam19TextField.setEditable(false);
        Stam19TextField.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        Stam19TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Stam19TextField.setText("2222");
        Stam19TextField.setToolTipText("自然回體量");

        Stam38Label.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        Stam38Label.setText("2倍消體場次(38體):");

        Stam38TextField.setEditable(false);
        Stam38TextField.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        Stam38TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Stam38TextField.setText("3333");
        Stam38TextField.setToolTipText("自然回體量");

        CollectedLabel.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        CollectedLabel.setText("道具量:");

        CollectedTextField.setEditable(false);
        CollectedTextField.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        CollectedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CollectedTextField.setText("4444");
        CollectedTextField.setToolTipText("自然回體量");

        CollectedPTLabel.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        CollectedPTLabel.setText("純道具PT:");

        CollectedPTTextField.setEditable(false);
        CollectedPTTextField.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        CollectedPTTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CollectedPTTextField.setText("5555");
        CollectedPTTextField.setToolTipText("自然回體量");

        CollectedToPTLabel.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        CollectedToPTLabel.setText("道具全消PT:");

        CollectedToPTTextField.setEditable(false);
        CollectedToPTTextField.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        CollectedToPTTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CollectedToPTTextField.setText("6666");
        CollectedToPTTextField.setToolTipText("自然回體量");

        TotalPTLabel.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        TotalPTLabel.setText("總PT:");

        TotalPTTextField.setEditable(false);
        TotalPTTextField.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        TotalPTTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TotalPTTextField.setText("7777");
        TotalPTTextField.setToolTipText("自然回體量");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(EventHrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(EventHrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(AutoRecStamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AutoRecStamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(PLvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(PLvSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(StarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(StarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Stam19Label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Stam19TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Stam38Label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Stam38TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CollectedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CollectedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CollectedPTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CollectedPTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CollectedToPTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CollectedToPTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(TotalPTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TotalPTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PLvSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PLvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EventHrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventHrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AutoRecStamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AutoRecStamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stam19Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stam19TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stam38Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stam38TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollectedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CollectedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollectedPTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CollectedPTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollectedToPTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CollectedToPTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalPTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EventHrSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EventHrSpinnerStateChanged
        // TODO add your handling code here:
        AutoRecStamTextField.setText(""+((Integer)EventHrSpinner.getValue() * 12));
        update();
    }//GEN-LAST:event_EventHrSpinnerStateChanged

    private void StarSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_StarSpinnerStateChanged
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_StarSpinnerStateChanged

    private void PLvSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PLvSpinnerStateChanged
        // TODO add your handling code here:
        if((Integer)PLvSpinner.getValue() > CGSS_Collect.maxPLV)
            PLvSpinner.setValue(CGSS_Collect.maxPLV);
        update();
    }//GEN-LAST:event_PLvSpinnerStateChanged

    private void update() {
        Stam19TextField.setText(""+CGSS_Collect.totalStaminaToPlay((Integer)StarSpinner.getValue(), (Integer)PLvSpinner.getValue(), Integer.parseInt(AutoRecStamTextField.getText()), singleStaminaPlay));
        Stam38TextField.setText(""+CGSS_Collect.totalStaminaToPlay((Integer)StarSpinner.getValue(), (Integer)PLvSpinner.getValue(), Integer.parseInt(AutoRecStamTextField.getText()), doubleStaminaPlay));
        CollectedTextField.setText(""+CGSS_Collect.totalNumCollect((Integer)StarSpinner.getValue(), (Integer)PLvSpinner.getValue(), Integer.parseInt(AutoRecStamTextField.getText()), singleStaminaPlay, singleStaminaCollect));
        CollectedPTTextField.setText(""+Float.parseFloat(CollectedTextField.getText()) / 2f);
        CollectedToPTTextField.setText(""+Float.parseFloat(CollectedTextField.getText()) / 150f * 320f);
        TotalPTTextField.setText(""+(Float.parseFloat(CollectedPTTextField.getText()) + Float.parseFloat(CollectedToPTTextField.getText()) ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CGSS_Collect_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CGSS_Collect_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CGSS_Collect_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CGSS_Collect_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CGSS_Collect_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutoRecStamLabel;
    private javax.swing.JTextField AutoRecStamTextField;
    private javax.swing.JLabel CollectedLabel;
    private javax.swing.JLabel CollectedPTLabel;
    private javax.swing.JTextField CollectedPTTextField;
    private javax.swing.JTextField CollectedTextField;
    private javax.swing.JLabel CollectedToPTLabel;
    private javax.swing.JTextField CollectedToPTTextField;
    private javax.swing.JLabel EventHrLabel;
    private javax.swing.JSpinner EventHrSpinner;
    private javax.swing.JLabel PLvLabel;
    private javax.swing.JSpinner PLvSpinner;
    private javax.swing.JLabel Stam19Label;
    private javax.swing.JTextField Stam19TextField;
    private javax.swing.JLabel Stam38Label;
    private javax.swing.JTextField Stam38TextField;
    private javax.swing.JLabel StarLabel;
    private javax.swing.JSpinner StarSpinner;
    private javax.swing.JLabel TotalPTLabel;
    private javax.swing.JTextField TotalPTTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
